# Checkov Configuration File
# This file configures Checkov security scanning for Terraform

# Skip specific checks (examples)
skip-check:
  # Skip if using custom encryption
  # - CKV_AZURE_33
  
  # Skip if using legacy resources temporarily
  # - CKV_AZURE_44

# Enable specific frameworks
framework:
  - terraform
  - secrets

# Enable compact output
compact: true

# Set quiet mode (only show failures)
quiet: false

# Output format
output: cli

# Include specific checks for Azure
check:
  - CKV_AZURE_1   # Ensure that Network Security Group's rule doesn't allow all traffic on SSH
  - CKV_AZURE_2   # Ensure that Network Security Group's rule doesn't allow all traffic on RDP  
  - CKV_AZURE_3   # Ensure no SQL Databases allow ingress from 0.0.0.0/0
  - CKV_AZURE_35  # Ensure default network access rule for Storage Accounts is set to deny
  - CKV_AZURE_36  # Ensure Storage Account default access is set to deny
  - CKV_AZURE_44  # Ensure Storage Account is using the latest version of TLS encryption
  - CKV_AZURE_53  # Ensure 'Trusted Microsoft Services' is enabled for Storage Account access
  - CKV_AZURE_59  # Ensure that Storage accounts disallow public read access to all the containers and blobs
  - CKV_AZURE_190 # Ensure that Storage blobs restrict public access

# Severity level
severity: HIGH,MEDIUM

# Enable soft fail (don't fail pipeline on security issues)
soft-fail: true

# Custom policies directory (if you have custom policies)
# external-checks-dir: ./custom-policies
