name: Main Terraform Trigger

on:
  pull_request:
    branches:
      - main

jobs:
  call-terraform-workflow:
    name: Call Terraform Workflow
    uses: ./.github/workflows/terraform.yml
    with:
      path: EA1/ACT1.2
  call-checkov-workflow:
    name: Call Terraform Workflow
    uses: ./.github/workflows/checkov.yml
    with:
      path: EA1/ACT1.2